branches:
  only:
    - master
language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  # depot tools (for git crrev-parse)
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  - export PATH=$PATH:$PWD/depot_tools
  # deploy key (no point in doing anything without it)
  - openssl aes-256-cbc -K $encrypted_d0eff0af4314_key -iv $encrypted_d0eff0af4314_iv -in deploy_key.enc -out deploy_key -d
  - chmod 0600 deploy_key
  - eval "$(ssh-agent -s)"
  - ssh-add deploy_key
script:
  - mkdir out
  # upstream wpt checkout (easy!)
  - git clone https://github.com/w3c/web-platform-tests.git
  # upstream wpt stats
  - ./wpt-stats.sh web-platform-tests > out/wpt-commits.csv
  # chromium checkout
  # use mirror, as github suppports --shallow-since and gives smaller packs
  - git clone --shallow-since=2017-01-01 https://github.com/scheib/chromium.git
  # chromium import stats
  - python wpt-import-stats.py chromium web-platform-tests
  - mv import-latencies.csv out/chromium-import-latency.csv
  # chromium export stats
  - python wpt-export-stats.py chromium
  - mv export-latencies.csv out/chromium-export-latency.csv
  # chromium usage stats
  - mv wpt-usage-stats chromium/third_party/WebKit/Tools/Scripts/
  - python chromium/third_party/WebKit/Tools/Scripts/wpt-usage-stats 2017-12-01 2018-01-01 > out/chromium-usage-stats.txt
  # bonus: chromium OWNERS check
  - ./chromium-wpt-owners.sh chromium/third_party/WebKit/LayoutTests/external/wpt > out/chromium-wpt-owners.txt
  - mv static/* out/
after_success:
  - git clone --branch gh-pages git@github.com:foolip/ecosystem-infra-stats.git gh-pages
  - rm -rf gh-pages/*
  - cp out/* gh-pages/
  - cd gh-pages
  - git config user.email "bot@foolip.org"
  - git config user.name "Automat af Ekosystem"
  - git add -A
  - git commit -m "Automatic update" -m "Using commit $TRAVIS_COMMIT" -m "https://travis-ci.org/foolip/ecosystem-infra-stats/builds/$TRAVIS_BUILD_ID"
  - git push
