branches:
  only:
    - master
script:
  - git clone https://github.com/w3c/web-platform-tests.git
  - ./wpt-stats.sh web-platform-tests
  - git clone --bare https://chromium.googlesource.com/chromium/src.git chromium.git
  - du -sh chromium.git
  - ./chromium-wpt-owners.sh chromium.git
