on: [pull_request, push]
name: lint
jobs:
  flake8:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - run: pip install flake8
    - run: flake8 --ignore=E501 *.py
